import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/globals/navbar";
import localFont from "next/font/local";
import Footer from "@/components/globals/footer";

const suisee = localFont({
  src: "../../public/fonts/Suisee.ttf",
  variable: "--font-suisee",
});

const lausanne = localFont({
  src: "../../public/fonts/Lausanne.ttf",
  variable: "--font-lausanne",
});
const TWKLausanne700 = localFont({
  src: "../../public/fonts/twk/TWKLausanne-700.woff",
  variable: "--font-TWKLausanne700",
});
const TWKLausanne500 = localFont({
  src: "../../public/fonts/twk/TWKLausanne-500.woff",
  variable: "--font-TWKLausanne500",
});


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${inter.variable} ${suisee.variable} ${lausanne.variable} ${TWKLausanne700.variable} ${TWKLausanne500.variable} antialiased`}
      ><Navbar/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
